// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbyqOCyE1XxVChsiIq-oj8TTUjnQHCFrg',
    appId: '1:562115108928:web:f7e6563313f4eb3a8dbfa5',
    messagingSenderId: '562115108928',
    projectId: 'dentiq-317c6',
    authDomain: 'dentiq-317c6.firebaseapp.com',
    storageBucket: 'dentiq-317c6.firebasestorage.app',
    measurementId: 'G-5RDBDM2MF0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZd9cOnAG-Yr_leIiVekTWgf3x7E8k9gs',
    appId: '1:562115108928:android:cf558a61bcb1f9468dbfa5',
    messagingSenderId: '562115108928',
    projectId: 'dentiq-317c6',
    storageBucket: 'dentiq-317c6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtNI9WTCeqID1keTc_NBIz-SIk-hMp4kM',
    appId: '1:562115108928:ios:4dcf00c2a82c4eb18dbfa5',
    messagingSenderId: '562115108928',
    projectId: 'dentiq-317c6',
    storageBucket: 'dentiq-317c6.firebasestorage.app',
    iosBundleId: 'com.example.dentiq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtNI9WTCeqID1keTc_NBIz-SIk-hMp4kM',
    appId: '1:562115108928:ios:4dcf00c2a82c4eb18dbfa5',
    messagingSenderId: '562115108928',
    projectId: 'dentiq-317c6',
    storageBucket: 'dentiq-317c6.firebasestorage.app',
    iosBundleId: 'com.example.dentiq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbyqOCyE1XxVChsiIq-oj8TTUjnQHCFrg',
    appId: '1:562115108928:web:37db6cbd171663ab8dbfa5',
    messagingSenderId: '562115108928',
    projectId: 'dentiq-317c6',
    authDomain: 'dentiq-317c6.firebaseapp.com',
    storageBucket: 'dentiq-317c6.firebasestorage.app',
    measurementId: 'G-JZZBKKQW0W',
  );
}
